#  First script 

In [1]:
import pandas as pd

In [2]:
ho_det=pd.read_csv("data.csv")

In [3]:
ho_det.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
ho_det.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64  
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    int64  
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [5]:
ho_det.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [6]:
# %matplotlib inline
# import matplotlib.pyplot as plt
# ho_det.hist(bins=20,figsize=(20,15))

# Splitting Training Data

In [7]:
# import numpy as np
# def split_training_data(data,test_rat):
#   np.random.seed(42)
#   shuffled=np.random.permutation(len(data))
#   test_size=int(len(data)*test_rat)
#   test_indice=shuffled[:test_size]
#   train_indice=shuffled[test_size:]
#   return data.iloc[train_indice], data.iloc[test_indice]

In [8]:
# train_set, test_set=split_training_data(ho_det,0.2)
# print(len(train_set),len(test_set))

In [9]:
from sklearn.model_selection import train_test_split
trainn_set,testt_set=train_test_split(ho_det, test_size=0.2, random_state=42)
print(len(trainn_set),len(testt_set))

404 102


In [10]:
from sklearn.model_selection import StratifiedShuffleSplit
split=StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=42)
for train_index, test_index in split.split(ho_det,ho_det['CHAS']):
  strat_train_set=ho_det.loc[train_index]
  strat_test_set=ho_det.loc[test_index]

In [11]:
strat_train_set['CHAS'].value_counts()

0    376
1     28
Name: CHAS, dtype: int64

# Change ho_det to strat_train_set

In [12]:
ho_det=strat_train_set.copy()

# Correlations

In [13]:
corr_mat=ho_det.corr()

In [14]:
corr_mat["MEDV"].sort_values(ascending=False)

MEDV       1.000000
RM         0.679894
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
LSTAT     -0.740494
Name: MEDV, dtype: float64

# Attribute Combinations

In [15]:
# ho_det["TAXPERRM"]=ho_det["TAX"]/ho_det["RM"]
# ho_det.head()
ho_det_aa=ho_det.drop("MEDV",axis=1)
ho_det_label=ho_det["MEDV"].copy()

# Fill NA values if any by median

In [16]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy="median")
imputer.fit(ho_det)

SimpleImputer(strategy='median')

In [17]:
imputer.statistics_

array([2.86735e-01, 0.00000e+00, 9.90000e+00, 0.00000e+00, 5.38000e-01,
       6.21000e+00, 7.82000e+01, 3.12220e+00, 5.00000e+00, 3.37000e+02,
       1.90000e+01, 3.90955e+02, 1.15700e+01, 2.11500e+01])

In [18]:
transform_data=pd.DataFrame(imputer.transform(ho_det),columns=ho_det.columns)
transform_data.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.279908   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.712983   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.878750   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.210000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.630250   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  404.000000  404.000000  
mean    12.791609   22.509406  
std      7.235740    9.385531  
min      1.730000    5.000000  
25%      6.847500   16.600000  
50%     11.570000   21.150000  
75%     17.102500   25.000000  
max     36.980000   50.000000

# Pipeline

In [19]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
my_pipeline= Pipeline([
    ('imputer', SimpleImputer(strategy="median")),
    ('std_scalar', StandardScaler())
])

In [20]:
ho_num_tr=my_pipeline.fit_transform(ho_det_aa)   #it gives array instead of DF

# Make Models

In [21]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

# model=LinearRegression()
# model=DecisionTreeRegressor()
model=RandomForestRegressor()
model.fit(ho_num_tr, ho_det_label)

RandomForestRegressor()

In [22]:
some_data=ho_det_aa.iloc[:5]
some_labels=ho_det_label.iloc[:5]
prepared_data=my_pipeline.transform(some_data)
model.predict(prepared_data)

array([22.508, 25.349, 16.778, 23.435, 23.54 ])

In [23]:
list(some_labels)

[21.9, 24.5, 16.7, 23.1, 23.0]

# Evaluating the model

In [24]:
import numpy as np
from sklearn.metrics import mean_squared_error
ho_pred=model.predict(ho_num_tr)
mean_sq_error=mean_squared_error(ho_det_label,ho_pred)
root_mse=np.sqrt(mean_sq_error)
print(mean_sq_error)
print(root_mse)

1.4029333861386126
1.1844548898707001


# Cross Validation - Better evaluation technique

In [25]:
from sklearn.model_selection import cross_val_score
scores=cross_val_score(model,ho_num_tr,ho_det_label, scoring="neg_mean_squared_error", cv=10)
rmse_scores=np.sqrt(-scores)

In [26]:
rmse_scores

array([2.87171201, 3.03661278, 4.40861407, 2.60264428, 3.45263028,
       2.69715761, 4.70252626, 3.27634467, 3.3833205 , 3.07101486])

In [27]:
rmse_scores_df=pd.DataFrame(rmse_scores).copy()
rmse_scores_df.describe()

0
count  10.000000
mean    3.350258
std     0.695749
min     2.602644
25%     2.912937
50%     3.173680
75%     3.435303
max     4.702526

# Save the Model

In [28]:
from joblib import dump, load
dump(model,'first.joblib')

['first.joblib']

# Testing the model on test data

In [29]:
test_data=strat_test_set.drop("MEDV",axis=1)
test_data_label=strat_test_set["MEDV"].copy()
test_prepared=my_pipeline.transform(test_data)
test_prediction=model.predict(test_prepared)
test_mse=mean_squared_error(test_data_label,test_prediction)
test_rmse=np.sqrt(test_mse)

In [30]:
test_rmse

2.9846743278182384